name: pull-request
on:
  pull_request:

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: terraform
        id: terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      - name: Terraform Syntax Check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: tfsec
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
